# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [30]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [31]:
# Import torch
import torch

# Create random tensor
A=torch.rand(7,7)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [32]:
# Create another random tensor
B=torch.rand(1,7)

# Perform matrix multiplication
AB=torch.matmul(A,B.T)
AB

tensor([[2.2430],
        [0.9277],
        [1.2816],
        [2.4873],
        [2.5144],
        [1.9350],
        [2.0938]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [41]:
# Set manual seed
torch.manual_seed(0)

# Create another random tensor
C=torch.rand(7,2)
D=torch.rand(2,1)

# Perform matrix multiplication
CD=torch.matmul(C,D)
CD


tensor([[0.5442],
        [0.0945],
        [0.4191],
        [0.6089],
        [0.4618],
        [0.3108],
        [0.0941]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [34]:
# Set random seed on the GPU
print(torch.cuda.is_available())
torch.cuda.manual_seed(0)

True



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [35]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()

# Create two random tensors on GPU
E=torch.rand(2,3,device='cuda:0')
F=torch.rand(2,3,device='cuda:0')

print(E,F)

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0') tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [36]:
# Perform matmul on tensor_A and tensor_B
EF=torch.matmul(E.T,F)
EF

tensor([[0.1525, 0.4531, 0.2796],
        [0.5374, 0.2079, 0.3640],
        [0.4462, 0.6783, 0.5284]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [37]:
# Find max
EF_max=torch.max(EF)
print(EF_max)

# Find min
EF_min=torch.min(EF)
print(EF_min)

tensor(0.6783, device='cuda:0')
tensor(0.1525, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [38]:
# Find arg max
EF_argmax=torch.argmax(EF)
print(EF_argmax)

# Find arg min
EF_argmin=torch.argmin(EF)
print(EF_argmin)

tensor(7, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [39]:
# Set seed
torch.manual_seed(10)

# Create random tensor
G=torch.rand(1,1,1,10)

# Remove single dimensions
G_squeezed=G.squeeze(dim=(0,1,2))

# Print out tensors and their shapes
print("Original Tensor")
print(G,G.shape)
print("Squeezed Tensor")
print(G_squeezed,G_squeezed.shape)

Original Tensor
tensor([[[[0.4581, 0.4829, 0.3125, 0.6150, 0.2139, 0.4118, 0.6938, 0.9693,
           0.6178, 0.3304]]]]) torch.Size([1, 1, 1, 10])
Squeezed Tensor
tensor([0.4581, 0.4829, 0.3125, 0.6150, 0.2139, 0.4118, 0.6938, 0.9693, 0.6178,
        0.3304]) torch.Size([10])
